server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
      hostname: ${HOSTNAME}
