server:
  port: 9003

spring:
  application:
    name: APPLICATION-SERVICE
  datasource:
    url: jdbc:postgresql://applicationservicedb/applications
    username: group18
    password: group18
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceregistry:8761/eureka

keycloak:
  auth-server-url: http://keycloak:8080
  realm: group18
  resource: application-service
  public-client: true
  ssl-required: none
  principal-attribute: preferred_username
