
server:
  port: 9000

spring:
  application:
    name: API-GATEWAY

#  cloud:
#    gateway:
#      routes:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
    hostname: ${HOSTNAME}
